steps:
  - name: ubuntu
    args:
      - '-c'
      - chmod 777 ./your-script.sh
      - ./your-script.sh
    entrypoint: bash
logsBucket: 'gs://cloud_b_logs/build_logs'
timeout: 600s
options:
  logging: 
      - GCS_ONLY
      - CLOUD_LOGGING_ONLY
